### ISSUE TITLE
Edge encoder shared between global and local

### ISSUE THREAD

**Issue by torfjelde** [MinkaiXu/GeoDiff#2]
First off, I want to just say that this is some really awesome work!

I'm currently considering applying the approach you've taken in GeoDiff to a particular conformation generation problem, and so I'm having a look through the code + trying to reproduce experiments atm.

While having a look I noticed that
https://github.com/MinkaiXu/GeoDiff/blob/d76991dd2edfda98631f001e542ecb933d310803/models/epsnet/dualenc.py#L186-L190
and
https://github.com/MinkaiXu/GeoDiff/blob/d76991dd2edfda98631f001e542ecb933d310803/models/epsnet/dualenc.py#L209-L213
are the same, leaving
https://github.com/MinkaiXu/GeoDiff/blob/d76991dd2edfda98631f001e542ecb933d310803/models/epsnet/dualenc.py#L62
unused.

Is this sharing of parameters intentional or just a typo? In the case it's the latter, I figured I should make you aware of it:)

**Comment by MinkaiXu** [comment]
Oh nope, definitely not the case. I think I should have used different networks. Let me check my git history...

**Comment by MinkaiXu** [comment]
Hi Tor, thanks a lot for your nice comment!

I checked my git history, and it seems I do share the parameters for my experiments... But yes it is a typo, and you can fix it in your own experiments!
For the empirical performance, I think since this module is relatively simple so it will not affect the performance a lot.

But one concern for correcting the repo now is that it will make the currently provided checkpoint work not very well. So for this repo, I may just keep the current code until find a time to re-run the whole model... : )

Thanks again for your check!
Minkai

**Comment by torfjelde** [comment]
| For the empirical performance, I think since this module is relatively simple so it will not affect the performance a lot.

Exactly. I specifically didn't use the word "bug" in my description because it's such a minor thing that it shouldn't matter that much + clearly the empirical performance of the model is already _very_ good:) But figured I'd at least make you aware in case it wasn't intentional 👍 Glad you found it useful!

| But one concern for correcting the repo now is that it will make the currently provided checkpoint work not very well. So for this repo, I may just keep the current code until find a time to re-run the whole model... : )

That makes sense:) As a tip: one thing you can always do is to create a separate branch for the code used in the publication and just point to the reader to that in the README on `#main`.

**Comment by MinkaiXu** [comment]
Thanks, Tor! And please ping me if there is any other question!
